spring.application.name=MagicFridgeAI

spring.datasource.url=${DATABASE_URL}
spring.datasource.driver=org.h2.Driver
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# Conf Flyway
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enable=true
spring.flyway.locations=classpath:db/migration

spring.config.import=optional:file:.env[.properties]

chatgpt.api.url=https://api.openai.com/v1/responses
spring.ai.openai.api-key=${API_KEY_CHATGPT}

